# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu
---
name: pylint
on:
  pull_request:
  push:
  schedule:
    - cron: "20 7 * * 1"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install pylint and requirements
        run: |
          python -m pip install --upgrade pip
          pip install pylint==2.7.2 pyyaml
          pip install -r requirements.txt
      - name: run pylint
        run: |
          pylint opnsense-fail2ban.py
